# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fuKN2c3y_SaRiFvtyXfNTtAjKHxJT9bo
"""

!pip install pytube

from pytube import YouTube
from pytube import Channel
from pytube import Playlist

# youtube_objct = YouTube('https://www.youtube.com/watch?v=sW4MJS3M6_E&list=PLDlIW055c7Rt_yvq8O-EZPg_kP2rSoMtv&index=2')

# yt_channel = Channel("https://youtube.com/c/GhostTradersGT")

PLAY_LIST = 'https://www.youtube.com/playlist?list=PLDlIW055c7Rt_yvq8O-EZPg_kP2rSoMtv'

yt_playlist = Playlist(PLAY_LIST)

yt_all_list = [video.title for video in yt_playlist.videos]

yt_all_video_url_list = [video.watch_url for video in yt_playlist.videos]

yt_all_video_url_list

# from google.colab import drive
# drive.mount('/content/drive')

import pytube

# print("Give URL:")
# url = input()

for url in yt_all_video_url_list:
    print(url)
    pytube.YouTube(url).streams.get_highest_resolution().download('../content/gt/videos')

!ls ../content/gt/videos -a

